Added any type to promises
Got an error like
 " node_modules/@zoomus/websdk/index.d.ts:67:32 - error TS2314: Generic type 'Promise<T>' requires 1 type argument(s).

67   function load(lang: string): Promise;
                                  ~~~~~~~


Error: node_modules/@zoomus/websdk/index.d.ts:73:54 - error TS2314: Generic type 'Promise<T>' requires 1 type argument(s).

73   function load(url: string | object, lang: string): Promise;
 "


Thats why added any type.